import { useState } from 'react'
import { LockKeyhole, LogIn } from 'lucide-react'
import { loginAdmin } from '../services/api'

export default function AdminLogin({onSuccess}:{onSuccess:()=>void}){
  const [user,setUser]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('')
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const result=await loginAdmin(user.trim(),password);sessionStorage.setItem('gringo-admin-auth','true');sessionStorage.setItem('gringo-admin-token',result.token);sessionStorage.setItem('gringo-admin-role',result.role);onSuccess()}catch(error){setError(error instanceof Error?error.message:'Usuario o contraseña incorrectos.')}}
  return <main className="flex min-h-screen items-center justify-center bg-[#fbf9f4] p-5"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-[#e6e1d8] bg-white p-8 shadow-xl"><div className="brand-mark mx-auto">▲</div><h1 className="font-display mt-5 text-center text-3xl font-semibold">Acceso administrador</h1><p className="mt-2 text-center text-sm text-[#68717a]">Ingresa para gestionar GringoShop.</p><label className="mt-7 block text-sm font-semibold">Usuario<input required value={user} onChange={e=>setUser(e.target.value)} className="mt-2 w-full rounded-md border p-3 font-normal" placeholder="Usuario"/></label><label className="mt-4 block text-sm font-semibold">Contraseña<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-md border p-3 font-normal" placeholder="Contraseña"/></label>{error&&<p className="mt-4 rounded-md bg-[#fff1e9] p-3 text-sm font-semibold text-[#a9553f]">{error}</p>}<button className="mt-5 flex w-full items-center justify-center gap-2 rounded-md bg-[#a9553f] p-3 font-bold text-white"><LogIn size={17}/> Entrar</button><p className="mt-5 flex items-center justify-center gap-2 text-xs text-[#68717a]"><LockKeyhole size={13}/> Acceso protegido</p></form></main>
}
