import { useState } from 'react'
import { Search } from 'lucide-react'
import { getOrdersByPhone } from '../services/api'

export default function BuyerOrderHistory(){
  const [phone,setPhone]=useState(''); const [orders,setOrders]=useState<any[]|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const search=async(e:React.FormEvent)=>{e.preventDefault();setError('');setOrders(null);if(!/^9\d{8}$/.test(phone)){setError('Ingresa un WhatsApp peruano válido: 9 dígitos y empieza con 9.');return}try{setLoading(true);setOrders(await getOrdersByPhone(phone))}catch{setError('No se pudo consultar tus reservas. Intenta nuevamente.')}finally{setLoading(false)}}
  const label=(status:string)=>({reserved:'Reservada',confirmed:'Confirmada',cancelled:'Cancelada',completed:'Completada'}[status]||status)
  return <section id="mis-reservas" className="mb-8 rounded-xl border border-[#e6e1d8] bg-white p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#a9553f]">Seguimiento</p><h2 className="font-display mt-2 text-3xl font-semibold">Consulta tus reservas</h2><p className="mt-2 text-sm text-[#68717a]">Ingresa el WhatsApp que usaste al reservar.</p></div><form onSubmit={search} className="flex w-full gap-2 sm:w-auto"><input inputMode="numeric" maxLength={9} value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,9))} placeholder="9XXXXXXXX" className="min-w-0 flex-1 rounded-md border p-3 text-sm outline-none focus:border-[#a9553f] sm:w-44"/><button disabled={loading} className="rounded-md bg-[#1c2b39] px-4 py-3 text-sm font-bold text-white disabled:opacity-50"><Search size={16}/></button></form></div>{error&&<p className="mt-4 rounded-md bg-[#fff1e9] p-3 text-sm font-semibold text-[#a9553f]">{error}</p>}{orders!==null&&<div className="mt-5 space-y-3">{orders.map(order=><div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-[#f5f2ec] p-4"><div><b className="block">{order.productName}</b><span className="text-xs text-[#68717a]">Reserva {order.id} · {new Date(order.createdAt).toLocaleDateString('es-PE')}</span></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${order.status==='cancelled'?'bg-[#fff1e9] text-[#a9553f]':order.status==='confirmed'||order.status==='completed'?'bg-[#e7f1e4] text-[#315b39]':'bg-white text-[#68717a]'}`}>{label(order.status)}</span></div>)}{!orders.length&&<p className="rounded-lg bg-[#f5f2ec] p-4 text-sm text-[#68717a]">No encontramos reservas con ese número.</p>}</div>}</section>
}
