import { useState } from 'react'
import { MessageCircle, Package, ShoppingBag, X } from 'lucide-react'

import Dialog from './Dialog'
import InstallmentNotice from './InstallmentNotice'

type Product = { id:string; name:string; brand:string; category:string; price:number; referencePrice:number; art:string; tag:string; currencySymbol?:string; image?:string; images?:string[] }

export default function ProductDetail({product,onClose,reserveHref,whatsapp}:{product:Product;onClose:()=>void;reserveHref?:string;whatsapp?:string}){
  const photos=product.images?.length?product.images:product.image?[product.image]:[]
  const [selectedPhoto,setSelectedPhoto]=useState(0)
  const symbol=product.currencySymbol||'S/'
  return <Dialog label={product.name} onClose={onClose}><article className="product-detail"><div className="grid md:grid-cols-2"><div className="product-gallery"><div className="product-photo flex min-h-72 items-center justify-center bg-gradient-to-br from-[#f0eee9] to-[#c9d0d0]">{photos.length?<img src={photos[selectedPhoto]||photos[0]} alt={`${product.name}, foto ${selectedPhoto+1}`} className="h-full w-full object-contain p-8"/>:<div className="missing-photo"><Package size={48} strokeWidth={1}/><span>Imagen no disponible</span></div>}</div>{photos.length>1&&<div className="gallery-thumbnails" aria-label="Fotos del producto">{photos.map((photo,index)=><button type="button" key={index} aria-label={`Ver foto ${index+1}`} aria-pressed={selectedPhoto===index} onClick={()=>setSelectedPhoto(index)}><img src={photo} alt=""/></button>)}</div>}</div><div className="p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a9553f]">{product.brand}</p><h2 className="font-display mt-2 text-3xl font-semibold leading-tight">{product.name}</h2></div><button onClick={onClose} aria-label="Cerrar"><X/></button></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-[#f5f2ec] px-3 py-1.5">{product.category}</span><span className="rounded-full bg-[#e7f1e4] px-3 py-1.5 text-[#315b39]">{product.tag}</span></div><p className="mt-6 text-sm leading-relaxed text-[#68717a]">Producto original de tienda oficial de Estados Unidos. Te ayudamos a traerlo con precio claro y seguimiento de tu reserva.</p><div className="mt-5 rounded-xl border border-[#e6e1d8] bg-[#f5f2ec] p-4"><span className="text-xs text-[#68717a]">Precio NegroShop</span><strong className="mt-1 block font-display text-3xl">{symbol} {product.price.toLocaleString('es-PE', {minimumFractionDigits:2, maximumFractionDigits:2})}</strong></div><InstallmentNotice whatsapp={whatsapp} productName={product.name}/><div className="mt-5 flex flex-col gap-2 sm:flex-row"><a href={reserveHref} target="_blank" rel="noreferrer" aria-disabled={!reserveHref} className="flex flex-1 items-center justify-center gap-2 rounded-md bg-[#1c2b39] p-3 text-sm font-bold text-white hover:bg-[#a9553f]"><ShoppingBag size={16}/> Reservar por WhatsApp</a>{whatsapp&&<a href={`https://wa.me/51${whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-md border border-[#315b39] px-4 py-3 text-sm font-bold text-[#315b39]"><MessageCircle size={16}/> WhatsApp</a>}</div></div></div></article></Dialog>
}
