import { useEffect, useState } from 'react'
import { Edit3, Eye, EyeOff, Save, X } from 'lucide-react'
import { getProducts, updateProduct } from '../services/api'

export default function ProductManagement() {
  const [products, setProducts] = useState<any[]>([])
  const [editing, setEditing] = useState<any | null>(null)
  const [message, setMessage] = useState('')
  const load = () => getProducts().then(setProducts)
  useEffect(() => { load().catch(() => setMessage('No se pudo cargar productos')) }, [])
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await updateProduct(editing.id, { name:String(form.get('name')), brand:String(form.get('brand')), price:Number(form.get('price')), referencePrice:Number(form.get('referencePrice')) }); setEditing(null); setMessage('Producto actualizado.'); await load() }
  const toggle = async (product:any) => { await updateProduct(product.id, { active: product.active === false }); setMessage(product.active === false ? 'Producto reactivado.' : 'Producto ocultado.'); await load() }
  return <section className="mt-6 rounded-xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl font-semibold">Productos publicados</h2><p className="mt-1 text-sm text-[#68717a]">Edita precios o controla qué aparece en la tienda.</p></div>{message&&<span className="text-sm font-bold text-[#315b39]">{message}</span>}</div><div className="mt-5 grid gap-3 md:grid-cols-2">{products.map(product=><div className={`rounded-lg border p-4 ${product.active===false?'bg-[#f1eee9] opacity-60':'bg-[#f5f2ec]'}`} key={product.id}><div className="flex items-start justify-between gap-3"><div><b className="block">{product.name}</b><small className="text-[#68717a]">{product.brand} · {product.category}</small><strong className="mt-2 block">S/ {Number(product.price).toLocaleString()}</strong></div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold">{product.active===false?'Oculto':'Activo'}</span></div><div className="mt-4 flex gap-2"><button onClick={()=>setEditing(product)} className="flex items-center gap-1 rounded-md bg-[#1c2b39] px-3 py-2 text-xs font-bold text-white"><Edit3 size={14}/> Editar</button><button onClick={()=>toggle(product)} className="flex items-center gap-1 rounded-md border border-[#a9553f] px-3 py-2 text-xs font-bold text-[#a9553f]">{product.active===false?<><Eye size={14}/> Reactivar</>:<><EyeOff size={14}/> Ocultar</>}</button></div></div>)}</div>{editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1c2b39]/60 p-4"><form onSubmit={save} className="w-full max-w-md rounded-xl bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-semibold">Editar producto</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><input name="name" defaultValue={editing.name} required className="mt-5 w-full rounded-md border p-3" placeholder="Nombre"/><input name="brand" defaultValue={editing.brand} required className="mt-3 w-full rounded-md border p-3" placeholder="Marca"/><input name="price" defaultValue={editing.price} required type="number" min="1" className="mt-3 w-full rounded-md border p-3" placeholder="Precio Gringo"/><input name="referencePrice" defaultValue={editing.referencePrice} required type="number" min="1" className="mt-3 w-full rounded-md border p-3" placeholder="Precio de tienda"/><div className="mt-4 flex gap-3"><button type="button" onClick={()=>setEditing(null)} className="w-1/2 rounded-md border p-3 font-bold">Cancelar</button><button className="flex w-1/2 items-center justify-center gap-1 rounded-md bg-[#a9553f] p-3 font-bold text-white"><Save size={15}/> Guardar</button></div></form></div>}</section>
}
