import { MessageCircle, ShoppingBag, X } from 'lucide-react'

type Product = { id:string; name:string; brand:string; category:string; price:number; referencePrice:number; reservationPercent:number; art:string; tag:string; currencySymbol?:string; image?:string }

export default function ProductDetail({product,onClose,onReserve,whatsapp}:{product:Product;onClose:()=>void;onReserve:()=>void;whatsapp?:string}){
  const symbol=product.currencySymbol||'S/'
  const reserve=product.price*product.reservationPercent/100
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1c2b39]/70 p-4" onClick={onClose}><article className="w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="grid md:grid-cols-2"><div className="product-photo flex min-h-72 items-center justify-center bg-gradient-to-br from-[#f0eee9] to-[#c9d0d0]">{product.image?<img src={product.image} alt={product.name} className="h-full w-full object-contain p-8"/>:<span className="product-symbol text-9xl">{product.art}</span>}</div><div className="p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#a9553f]">{product.brand}</p><h2 className="font-display mt-2 text-3xl font-semibold leading-tight">{product.name}</h2></div><button onClick={onClose} aria-label="Cerrar"><X/></button></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-[#f5f2ec] px-3 py-1.5">{product.category}</span><span className="rounded-full bg-[#e7f1e4] px-3 py-1.5 text-[#315b39]">{product.tag}</span></div><p className="mt-6 text-sm leading-relaxed text-[#68717a]">Producto original de tienda oficial de Estados Unidos. Te ayudamos a traerlo con precio claro y seguimiento de tu reserva.</p><div className="mt-5 rounded-xl border border-[#e6e1d8] bg-[#f5f2ec] p-4"><span className="text-xs text-[#68717a]">Precio Gringo</span><strong className="mt-1 block font-display text-3xl">{symbol} {product.price.toLocaleString()}</strong><div className="mt-3 border-t border-[#ded8ce] pt-3 text-sm"><span>Reserva {product.reservationPercent}%</span><strong className="float-right">{symbol} {reserve.toLocaleString()}</strong></div><p className="mt-2 text-xs text-[#68717a]">Saldo restante al recibir: {symbol} {(product.price-reserve).toLocaleString()}</p></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><button onClick={onReserve} className="flex flex-1 items-center justify-center gap-2 rounded-md bg-[#1c2b39] p-3 text-sm font-bold text-white hover:bg-[#a9553f]"><ShoppingBag size={16}/> Reservar producto</button>{whatsapp&&<a href={`https://wa.me/51${whatsapp}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-2 rounded-md border border-[#315b39] px-4 py-3 text-sm font-bold text-[#315b39]"><MessageCircle size={16}/> WhatsApp</a>}</div></div></div></article></div>
}
