import { useEffect, useState } from 'react'
import { getSettings, updateSettings } from '../services/api'

export default function SettingsManagement(){
  const [form,setForm]=useState(()=>{try{return JSON.parse(localStorage.getItem('gringo-settings-draft')||'null')||{reservationPercent:50,whatsapp:'',currency:'PEN',welcomeMessage:'Compra directo de tiendas de Estados Unidos.'}}catch{return {reservationPercent:50,whatsapp:'',currency:'PEN',welcomeMessage:'Compra directo de tiendas de Estados Unidos.'}}})
  const [status,setStatus]=useState(''); const [saving,setSaving]=useState(false)
  useEffect(()=>{const draft=localStorage.getItem('gringo-settings-draft');if(draft)return;getSettings().then(setForm).catch(()=>setStatus('No se pudo cargar la configuración'))},[])
  const change=(key:string,value:string|number)=>setForm(current=>{const next={...current,[key]:value};localStorage.setItem('gringo-settings-draft',JSON.stringify(next));return next})
  const changePercent=(value:string)=>{const clean=value.replace(/\D/g,'').replace(/^0+(?=\d)/,'');change('reservationPercent',clean===''?'':Number(clean))}
  useEffect(()=>{if(!localStorage.getItem('gringo-settings-draft')||!form.reservationPercent)return;const timer=window.setTimeout(()=>{updateSettings({...form,reservationPercent:Number(form.reservationPercent)}).catch(()=>{})},700);return()=>window.clearTimeout(timer)},[form])
  const save=async(e:React.FormEvent)=>{e.preventDefault();setStatus('');if(!form.reservationPercent||Number(form.reservationPercent)<1||Number(form.reservationPercent)>100){setStatus('El adelanto debe estar entre 1 y 100.');return}if(form.whatsapp&&!/^9\d{8}$/.test(form.whatsapp)){setStatus('WhatsApp inválido: debe tener 9 dígitos y comenzar con 9.');return}try{setSaving(true);const saved=await updateSettings({...form,reservationPercent:Number(form.reservationPercent)});setForm(saved);localStorage.removeItem('gringo-settings-draft');setStatus('Configuración guardada correctamente.')}catch(error){setStatus(error instanceof Error?error.message:'No se pudo guardar la configuración')}finally{setSaving(false)}}
  return <section id="configuracion" className="mt-6 rounded-xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-display text-2xl font-semibold">Configuración</h2><p className="mt-1 text-sm text-[#68717a]">Estos valores se usarán como reglas generales de la tienda.</p></div><span className="rounded-full bg-[#f5f2ec] px-3 py-1 text-xs font-bold text-[#68717a]">Guardado en el backend</span></div><form onSubmit={save} className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Adelanto de reserva (%)<input required min="1" max="100" inputMode="numeric" type="text" value={form.reservationPercent} onChange={e=>changePercent(e.target.value)} className="mt-2 w-full rounded-md border p-3 font-normal"/><span className="mt-1 block text-xs font-normal text-[#68717a]">Porcentaje que el cliente debe adelantar.</span></label><label className="text-sm font-semibold">WhatsApp de la tienda<input inputMode="numeric" maxLength={9} value={form.whatsapp} onChange={e=>change('whatsapp',e.target.value.replace(/\D/g,'').slice(0,9))} placeholder="9XXXXXXXX" className="mt-2 w-full rounded-md border p-3 font-normal"/><span className="mt-1 block text-xs font-normal text-[#68717a]">Opcional. Debe comenzar con 9 y tener 9 dígitos.</span></label><label className="text-sm font-semibold">Moneda<select value={form.currency} onChange={e=>change('currency',e.target.value)} className="mt-2 w-full rounded-md border bg-white p-3 font-normal"><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></label><label className="text-sm font-semibold md:col-span-2">Mensaje principal<textarea required rows={3} value={form.welcomeMessage} onChange={e=>change('welcomeMessage',e.target.value)} className="mt-2 w-full rounded-md border p-3 font-normal"/></label><div className="flex items-center gap-4 md:col-span-2"><button disabled={saving} className="rounded-md bg-[#a9553f] px-5 py-3 font-bold text-white disabled:opacity-50">{saving?'Guardando…':'Guardar configuración'}</button>{status&&<p className={`text-sm font-semibold ${status.includes('correctamente')?'text-[#315b39]':'text-[#a9553f]'}`}>{status}</p>}</div></form></section>
}
