import http from 'node:http'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync, mkdirSync, readFileSync } from 'node:fs'
import { DatabaseSync } from 'node:sqlite'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { randomUUID, scryptSync, timingSafeEqual } from 'node:crypto'
import { createProduct } from '../domain/entities/Product.mjs'
import { createOrder } from '../domain/entities/Order.mjs'
import { changeQuoteStatus, createQuote } from '../domain/entities/Quote.mjs'
import { changeOrderStatus } from '../domain/entities/Order.mjs'

const root = path.dirname(fileURLToPath(import.meta.url))
const dataDir = path.join(root, '..', 'data')
const dbFile = path.join(dataDir, 'db.json')
const sqliteFile = path.join(dataDir, 'gringo-shop.sqlite')
const adminSessions = new Map()
const corsOrigin = process.env.CORS_ORIGIN || '*'
const seed = { products: [], quotes: [], orders: [], settings: { reservationPercent: 50, whatsapp: '', currency: 'PEN', welcomeMessage: 'Compra directo de tiendas de Estados Unidos.' } }
mkdirSync(dataDir, { recursive: true })
const sqlite = new DatabaseSync(sqliteFile)
sqlite.exec('CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS quotes (id TEXT PRIMARY KEY, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT \'admin\', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);')
function hashPassword(password) { const salt=randomUUID(); return `${salt}:${scryptSync(password,salt,64).toString('hex')}` }
function verifyPassword(password, stored) { const [salt,hash]=stored.split(':'); if(!salt||!hash)return false; const actual=scryptSync(password,salt,64); const expected=Buffer.from(hash,'hex'); return actual.length===expected.length&&timingSafeEqual(actual,expected) }
if (!sqlite.prepare('SELECT id FROM users LIMIT 1').get()) sqlite.prepare('INSERT INTO users (id,username,password_hash,role,created_at) VALUES (?,?,?,?,?)').run(randomUUID(), process.env.ADMIN_USER || 'admin', hashPassword(process.env.ADMIN_PASSWORD || 'gringo2026'), 'admin', new Date().toISOString())
if (sqlite.prepare('SELECT COUNT(*) AS count FROM products').get().count === 0 && existsSync(dbFile)) { try { const legacy = JSON.parse(readFileSync(dbFile, 'utf8')); const insertProduct=sqlite.prepare('INSERT OR IGNORE INTO products (id,data) VALUES (?,?)'); for (const item of legacy.products||[]) insertProduct.run(item.id, JSON.stringify(item)); const insertOrder=sqlite.prepare('INSERT OR IGNORE INTO orders (id,data) VALUES (?,?)'); for (const item of legacy.orders||[]) insertOrder.run(item.id, JSON.stringify(item)); const insertQuote=sqlite.prepare('INSERT OR IGNORE INTO quotes (id,data) VALUES (?,?)'); for (const item of legacy.quotes||[]) insertQuote.run(item.id, JSON.stringify(item)); const settings={...seed.settings,...(legacy.settings||{})}; sqlite.prepare('INSERT OR REPLACE INTO settings (key,value) VALUES (?,?)').run('store',JSON.stringify(settings)) } catch {} }
if (!sqlite.prepare('SELECT value FROM settings WHERE key = ?').get('store')) sqlite.prepare('INSERT INTO settings (key,value) VALUES (?,?)').run('store', JSON.stringify(seed.settings))
function db() { const read=(table)=>sqlite.prepare(`SELECT data FROM ${table}`).all().map(row=>JSON.parse(row.data)); const settings=JSON.parse(sqlite.prepare('SELECT value FROM settings WHERE key = ?').get('store').value); return { products:read('products'), quotes:read('quotes'), orders:read('orders'), settings } }
function save(data) { const replace=(table,items)=>{sqlite.prepare(`DELETE FROM ${table}`).run(); const insert=sqlite.prepare(`INSERT INTO ${table} (id,data) VALUES (?,?)`); for(const item of items) insert.run(item.id,JSON.stringify(item))}; replace('products',data.products); replace('orders',data.orders); replace('quotes',data.quotes); sqlite.prepare('INSERT OR REPLACE INTO settings (key,value) VALUES (?,?)').run('store',JSON.stringify(data.settings||seed.settings)); return data }
function json(res, status, body) { res.writeHead(status, { 'content-type': 'application/json', 'access-control-allow-origin': corsOrigin, 'access-control-allow-methods': 'GET,POST,PATCH,OPTIONS', 'access-control-allow-headers': 'content-type, authorization' }); res.end(JSON.stringify(body)) }
async function body(req) { let raw=''; for await (const chunk of req) raw += chunk; return raw ? JSON.parse(raw) : {} }
function isAdminRoute(url, req) { return ( (url.pathname === '/api/settings' && req.method === 'PATCH') || (url.pathname === '/api/backup' && req.method === 'GET') || (url.pathname === '/api/me/password' && req.method === 'PATCH') || (url.pathname === '/api/users' && ['GET','POST'].includes(req.method)) || (url.pathname.startsWith('/api/users/') && req.method === 'PATCH') || (url.pathname === '/api/customers' && req.method === 'GET') || (url.pathname === '/api/orders' && req.method === 'GET' && !url.searchParams.has('phone')) || (url.pathname === '/api/quotes' && req.method === 'GET') || (url.pathname === '/api/products' && req.method === 'POST') || (url.pathname.startsWith('/api/products/') && req.method === 'PATCH') || (url.pathname.startsWith('/api/orders/') && req.method === 'PATCH') || (url.pathname.startsWith('/api/quotes/') && req.method === 'PATCH') ) }
function adminSession(req) { const value = req.headers.authorization || ''; return value.startsWith('Bearer ') ? adminSessions.get(value.slice(7)) : null }
function hasAdminToken(req) { return Boolean(adminSession(req)) }

const server = http.createServer(async (req, res) => {
  if (req.method === 'OPTIONS') return json(res, 204, {})
  const url = new URL(req.url, 'http://localhost'); const data = await db()
  try {
    if (req.method === 'POST' && url.pathname === '/api/auth/login') { const input = await body(req); const user = sqlite.prepare('SELECT id,username,password_hash,role FROM users WHERE username = ? AND active = 1').get(String(input.username || '').trim()); if (!user || !verifyPassword(String(input.password || ''), user.password_hash)) return json(res, 401, { error: 'Usuario o contraseña incorrectos.' }); const token = `admin-${randomUUID()}`; adminSessions.set(token, { userId:user.id, username:user.username, role:user.role }); return json(res, 200, { authenticated: true, role: user.role, username:user.username, token }) }
    if (isAdminRoute(url, req) && !hasAdminToken(req)) return json(res, 401, { error: 'Sesión administrativa inválida o expirada.' })
    if (req.method === 'GET' && url.pathname === '/api/backup') { res.writeHead(200, { 'content-type':'application/x-sqlite3', 'content-disposition':`attachment; filename="gringo-shop-${new Date().toISOString().slice(0,10)}.sqlite`, 'access-control-allow-origin':'*', 'access-control-allow-headers':'content-type, authorization' }); return res.end(readFileSync(sqliteFile)) }
    if (url.pathname === '/api/settings' && req.method === 'PATCH' && adminSession(req)?.role !== 'admin') return json(res, 403, { error: 'Solo un administrador puede cambiar la configuración.' })
    if (req.method === 'PATCH' && url.pathname === '/api/me/password') { const input=await body(req); const session=adminSession(req); const current=sqlite.prepare('SELECT password_hash FROM users WHERE id=? AND active=1').get(session.userId); if(!current||!verifyPassword(String(input.currentPassword||''),current.password_hash)) return json(res,400,{error:'La contraseña actual no es correcta.'}); if(String(input.newPassword||'').length<8)return json(res,400,{error:'La nueva contraseña debe tener al menos 8 caracteres.'}); sqlite.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(String(input.newPassword)),session.userId); adminSessions.clear(); return json(res,200,{ok:true}) }
    if (url.pathname === '/api/users' && adminSession(req)?.role !== 'admin') return json(res, 403, { error: 'Solo un administrador puede gestionar usuarios.' })
    if (url.pathname.startsWith('/api/users/') && adminSession(req)?.role !== 'admin') return json(res, 403, { error: 'Solo un administrador puede gestionar usuarios.' })
    if (req.method === 'GET' && url.pathname === '/api/users') return json(res, 200, sqlite.prepare('SELECT id,username,role,active,created_at AS createdAt FROM users ORDER BY username').all())
    if (req.method === 'POST' && url.pathname === '/api/users') { const input=await body(req); const username=String(input.username||'').trim(); const password=String(input.password||''); const role=input.role==='editor'?'editor':'admin'; if(!/^[a-zA-Z0-9._-]{3,30}$/.test(username)) return json(res,400,{error:'El usuario debe tener entre 3 y 30 caracteres.'}); if(password.length<8) return json(res,400,{error:'La contraseña debe tener al menos 8 caracteres.'}); try { const user={id:randomUUID(),username,password_hash:hashPassword(password),role,active:1,created_at:new Date().toISOString()}; sqlite.prepare('INSERT INTO users (id,username,password_hash,role,active,created_at) VALUES (?,?,?,?,?,?)').run(user.id,user.username,user.password_hash,user.role,user.active,user.created_at); return json(res,201,{id:user.id,username:user.username,role:user.role,active:true,createdAt:user.created_at}) } catch { return json(res,409,{error:'Ese usuario ya existe.'}) }
    }
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/users/')) { const id=url.pathname.split('/').pop(); const input=await body(req); const current=sqlite.prepare('SELECT id,username,role,active FROM users WHERE id=?').get(id); if(!current)return json(res,404,{error:'Usuario no encontrado.'}); if(id===adminSession(req)?.userId&&input.active===false)return json(res,400,{error:'No puedes desactivar tu propio usuario.'}); const role=input.role==='editor'?'editor':input.role==='admin'?'admin':current.role; const active=input.active===undefined?current.active:(input.active?1:0); if(input.password!==undefined&&String(input.password).length<8)return json(res,400,{error:'La contraseña debe tener al menos 8 caracteres.'}); const passwordHash=input.password?hashPassword(String(input.password)):undefined; sqlite.prepare(`UPDATE users SET role=?, active=?${passwordHash?', password_hash=?':''} WHERE id=?`).run(...(passwordHash?[role,active,passwordHash,id]:[role,active,id])); return json(res,200,{...current,role,active:Boolean(active)}) }
    if (req.method === 'GET' && url.pathname === '/api/health') return json(res, 200, { ok: true, service: 'gringo-shop-back' })
    if (req.method === 'GET' && url.pathname === '/api/settings') return json(res, 200, { ...seed.settings, ...(data.settings || {}) })
    if (req.method === 'PATCH' && url.pathname === '/api/settings') { const input = await body(req); const current = { ...seed.settings, ...(data.settings || {}) }; const next = { ...current, reservationPercent: Number(input.reservationPercent ?? current.reservationPercent), whatsapp: String(input.whatsapp ?? current.whatsapp).replace(/\D/g, '').slice(0, 9), currency: String(input.currency ?? current.currency), welcomeMessage: String(input.welcomeMessage ?? current.welcomeMessage).trim() }; if (next.reservationPercent < 1 || next.reservationPercent > 100) return json(res, 400, { error: 'El adelanto debe estar entre 1 y 100.' }); if (next.whatsapp && !/^9\d{8}$/.test(next.whatsapp)) return json(res, 400, { error: 'El WhatsApp debe tener 9 dígitos y comenzar con 9.' }); data.settings = next; await save(data); return json(res, 200, next) }
    if (req.method === 'GET' && url.pathname === '/api/products') return json(res, 200, data.products)
    if (req.method === 'GET' && url.pathname === '/api/categories') return json(res, 200, [...new Set(data.products.filter(product => product.active !== false).map(product => product.category).filter(Boolean))].sort())
    if (req.method === 'POST' && url.pathname === '/api/products') { const product = createProduct(await body(req)); data.products.push(product); await save(data); return json(res, 201, product) }
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/products/')) { const id = url.pathname.split('/').pop(); const input = await body(req); const index = data.products.findIndex(product => product.id === id); if (index < 0) return json(res, 404, { error: 'Producto no encontrado' }); data.products[index] = { ...data.products[index], ...input, id, price: input.price === undefined ? data.products[index].price : Number(input.price), referencePrice: input.referencePrice === undefined ? data.products[index].referencePrice : Number(input.referencePrice), updatedAt: new Date().toISOString() }; await save(data); return json(res, 200, data.products[index]) }
    if (req.method === 'POST' && url.pathname === '/api/quotes') { const quote = createQuote(await body(req)); data.quotes.push(quote); await save(data); return json(res, 201, quote) }
    if (req.method === 'POST' && url.pathname === '/api/orders') { const order = createOrder(await body(req)); data.orders.push(order); await save(data); return json(res, 201, order) }
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/orders/')) { const id = url.pathname.split('/').pop(); const input = await body(req); const index = data.orders.findIndex(order => order.id === id); if (index < 0) return json(res, 404, { error: 'Reserva no encontrada' }); data.orders[index] = changeOrderStatus(data.orders[index], input.status); await save(data); return json(res, 200, data.orders[index]) }
    if (req.method === 'GET' && url.pathname === '/api/orders') { const phone=url.searchParams.get('phone'); return json(res, 200, phone ? data.orders.filter(order=>order.phone===phone) : data.orders) }
    if (req.method === 'GET' && url.pathname === '/api/customers') { const customers = Object.values(data.orders.reduce((map, order) => { const key = order.phone; if (!map[key]) map[key] = { phone: order.phone, name: order.customer, orders: 0, products: [], lastActivity: order.updatedAt || order.createdAt }; map[key].orders += 1; if (!map[key].products.includes(order.productName)) map[key].products.push(order.productName); map[key].lastActivity = [map[key].lastActivity, order.updatedAt || order.createdAt].sort().at(-1); return map }, {})); return json(res, 200, customers) }
    if (req.method === 'GET' && url.pathname === '/api/quotes') return json(res, 200, data.quotes)
    if (req.method === 'PATCH' && url.pathname.startsWith('/api/quotes/')) { const id = url.pathname.split('/').pop(); const input = await body(req); const index = data.quotes.findIndex(quote => quote.id === id); if (index < 0) return json(res, 404, { error: 'Cotización no encontrada' }); data.quotes[index] = changeQuoteStatus(data.quotes[index], input.status); await save(data); return json(res, 200, data.quotes[index]) }
    return json(res, 404, { error: 'Ruta no encontrada' })
  } catch (error) { return json(res, 500, { error: error.message }) }
})
const port = Number(process.env.PORT || 4000)
server.listen(port, () => console.log(`GringoShop API: http://localhost:${port}`))
