import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight, Check, ExternalLink, MessageCircle, Package, Plus, Search, X } from 'lucide-react'
import { createProduct, getCategories, getOrders, getProducts, getQuotes, updateOrderStatus, updateQuoteStatus } from '../../services/api'
import ProductManagement from '../../components/ProductManagement'
import CustomerManagement from '../../components/CustomerManagement'
import SettingsManagement from '../../components/SettingsManagement'
import UserManagement from '../../components/UserManagement'
import PasswordManagement from '../../components/PasswordManagement'
import BackupManagement from '../../components/BackupManagement'
import AdminSidebar from '../../components/AdminSidebar'
import RealtimeNotifications from '../../components/RealtimeNotifications'
import Dialog from '../../components/Dialog'
import ProductPhotoUpload from '../../components/ProductPhotoUpload'
import { optimizeProductImage } from '../../utils/productImages'
import { LanguageSwitcher } from '../../i18n'
type Order = {id:string;customer:string;productName:string;phone:string;status:string}
type Quote = {id:string;customer:string;name:string;phone:string;status:string;notes?:string;link?:string}
const titles:Record<string,string> = {inicio:'Resumen de tu tienda',reservas:'Reservas',productos:'Productos',cotizaciones:'Cotizaciones',clientes:'Clientes',configuracion:'Configuración'}
const descriptions:Record<string,string> = {inicio:'Todo lo que necesitas para organizar el día.',reservas:'Revisa las solicitudes y confirma las compras de tus clientes.',productos:'Organiza el catálogo que ven tus compradores.',cotizaciones:'Da seguimiento a los productos que tus clientes quieren traer.',clientes:'Conoce a los compradores y sus reservas.',configuracion:'Personaliza tu tienda y administra el acceso al panel.'}
export default function AdminPage({role,onLogout}:{role:string;onLogout:()=>void}) {
  const [active,setActive]=useState('inicio')
  useEffect(()=>{document.title='NegroShop · Administración'},[])
  const [products,setProducts]=useState<{id:string;active?:boolean}[]>([])
  const [orders,setOrders]=useState<Order[]>([])
  const [quotes,setQuotes]=useState<Quote[]>([])
  const [categories,setCategories]=useState<string[]>([])
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const [message,setMessage]=useState('')
  const [open,setOpen]=useState(false)
  const [customCategory,setCustomCategory]=useState(false)
  const [images,setImages]=useState<string[]>([])
  const [processingPhotos,setProcessingPhotos]=useState(false)
  const [removeCoverBackground,setRemoveCoverBackground]=useState(true)
  const [publishing,setPublishing]=useState(false)
  const [publishError,setPublishError]=useState('')
  const [busy,setBusy]=useState<string|null>(null)
  const [query,setQuery]=useState('')
  const [status,setStatus]=useState('all')
  const load = async()=>{const [p,o,q,c]=await Promise.all([getProducts(),getOrders(),getQuotes(),getCategories()]);setProducts(p);setOrders(o);setQuotes(q);setCategories(c);setError('')}
  useEffect(()=>{
    const navigate=()=>{const next=window.location.hash.slice(1);setActive(titles[next]&&(next!=='configuracion'||role==='admin')?next:'inicio');setQuery('');setStatus('all')}
    navigate();window.addEventListener('hashchange',navigate)
    return ()=>window.removeEventListener('hashchange',navigate)
  },[role])
  useEffect(()=>{let mounted=true;const refresh=async()=>{try{await load()}catch{if(mounted)setError('No pudimos actualizar el panel. Revisa tu conexión y vuelve a intentarlo.')}finally{if(mounted)setLoading(false)}};void refresh();const timer=window.setInterval(()=>{if(!document.hidden)void refresh()},5000);return()=>{mounted=false;window.clearInterval(timer)}},[])
  const pendingOrders=orders.filter(o=>o.status==='reserved')
  const pendingQuotes=quotes.filter(q=>q.status==='pending')
  const updateOrder=async(id:string,next:'confirmed'|'cancelled')=>{setBusy(id);try{await updateOrderStatus(id,next);await load();setMessage(next==='confirmed'?'Reserva confirmada.':'Reserva cancelada.')}catch{setError('No pudimos actualizar la reserva. Intenta nuevamente.')}finally{setBusy(null)}}
  const updateQuote=async(id:string,next:'contacted'|'closed')=>{setBusy(id);try{await updateQuoteStatus(id,next);await load();setMessage(next==='contacted'?'Cotización marcada como contactada.':'Cotización cerrada.')}catch{setError('No pudimos actualizar la cotización. Intenta nuevamente.')}finally{setBusy(null)}}
  const publish=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();if(publishing||processingPhotos)return
    const form=new FormData(event.currentTarget)
    const category=String(form.get(customCategory?'customCategory':'category')).trim()
    setPublishing(true);setPublishError('')
    try{let photos=images;if(removeCoverBackground&&images.length){const {removeBackground}=await import('@imgly/background-removal');const cover=await removeBackground(await (await fetch(images[0])).blob());photos=[await optimizeProductImage(cover),...images.slice(1)]}await createProduct({name:String(form.get('name')).trim(),brand:String(form.get('brand')).trim(),category,price:Number(form.get('price')),referencePrice:Number(form.get('referencePrice')),image:photos[0]||'',images:photos});setOpen(false);setMessage('Producto publicado. Ya aparece en el catálogo.');await load()}catch(failure){setPublishError(failure instanceof Error?failure.message:'No pudimos publicar el producto. Intenta nuevamente.')}finally{setPublishing(false)}
  }
  const visibleOrders=(active==='inicio'?pendingOrders:orders).filter(o=>(status==='all'||o.status===status)&&`${o.customer} ${o.productName} ${o.phone}`.toLowerCase().includes(query.toLowerCase()))
  const visibleQuotes=quotes.filter(q=>(status==='all'||q.status===status)&&`${q.name} ${q.customer} ${q.phone}`.toLowerCase().includes(query.toLowerCase()))
  const filters=<div className="admin-filters"><label><Search size={17}/><span className="sr-only">Buscar solicitudes</span><input type="search" placeholder="Buscar cliente, producto o WhatsApp…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrar por estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option>{(active==='cotizaciones'?[['pending','Pendiente'],['contacted','Contactada'],['closed','Cerrada']]:[['reserved','Pendiente'],['confirmed','Confirmada'],['cancelled','Cancelada'],['completed','Completada']]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>
  return <div className="admin-app"><AdminSidebar role={role} active={active} onLogout={onLogout}/><div className="admin-content"><header className="admin-topbar"><span>Administración <span>/ {active==='inicio'?'Resumen':titles[active]}</span></span><div className="admin-topbar-actions"><LanguageSwitcher/><RealtimeNotifications/></div></header><main className="admin-main"><div className="admin-page-heading"><div><h1>{titles[active]}</h1><p>{descriptions[active]}</p></div><button className="primary-button" onClick={()=>{setOpen(true);setPublishError('');setCustomCategory(false);setImages([]);setRemoveCoverBackground(true)}}><Plus size={18}/>Publicar producto</button></div>
    {error&&<div role="alert" className="error-message"><p>{error}</p><button onClick={()=>load().catch(()=>setError('La conexión sigue sin estar disponible. Intenta nuevamente.'))}>Reintentar</button></div>}{message&&<div role="status" className="success-message">{message}<button aria-label="Cerrar mensaje" onClick={()=>setMessage('')}><X size={18}/></button></div>}
    {active==='inicio'&&<><div className="admin-summary" aria-busy={loading}>{[['Productos activos',products.filter(p=>p.active!==false).length,'productos'],['Reservas por confirmar',pendingOrders.length,'reservas'],['Cotizaciones pendientes',pendingQuotes.length,'cotizaciones'],['Total de clientes',new Set(orders.map(o=>o.phone)).size,'clientes']].map(([label,value,target])=><a href={`#${target}`} key={label}><span>{label}</span><strong>{loading?'—':value}</strong><span className="summary-link">Ver detalle <ArrowRight size={15}/></span></a>)}</div><div className="admin-attention"><div><h2>{loading?'Cargando actividad…':pendingOrders.length+pendingQuotes.length?'Hay solicitudes por atender':'Todo al día'}</h2><p>{pendingOrders.length+pendingQuotes.length?'Revisa las reservas y cotizaciones pendientes para continuar con cada compra.':'Las nuevas solicitudes de tus clientes aparecerán aquí.'}</p></div><a href="#cotizaciones">Ver cotizaciones <ArrowRight size={16}/></a></div></>}
    {(active==='inicio'||active==='reservas')&&<section id="reservas" className="admin-panel"><div className="admin-panel-heading"><div><h2>{active==='inicio'?'Reservas por confirmar':'Listado de reservas'}</h2><p>{active==='inicio'?'Solicitudes que necesitan tu atención.':`${orders.length} reservas registradas`}</p></div>{active==='inicio'&&<a href="#reservas">Ver todas <ArrowRight size={15}/></a>}</div>{active==='reservas'&&filters}<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Cliente</th><th>Producto</th><th>WhatsApp</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="admin-empty">Cargando reservas…</td></tr>:visibleOrders.map(o=><tr key={o.id}><td><strong>{o.customer}</strong></td><td>{o.productName}</td><td className="phone-cell">{o.phone}</td><td><span className={`admin-status ${o.status}`}>{({reserved:'Pendiente',confirmed:'Confirmada',cancelled:'Cancelada',completed:'Completada'} as Record<string,string>)[o.status]||o.status}</span></td><td><div className="row-actions">{o.status==='reserved'?<><button disabled={busy!==null} onClick={()=>updateOrder(o.id,'confirmed')} className="action-confirm"><Check size={14}/>{busy===o.id?'Guardando…':'Confirmar'}</button><button disabled={busy!==null} onClick={()=>updateOrder(o.id,'cancelled')}>Cancelar</button></>:<span className="muted">Sin acciones pendientes</span>}</div></td></tr>)}{!loading&&!visibleOrders.length&&<tr><td colSpan={5} className="admin-empty"><Package size={26}/><strong>{query||status!=='all'?'No encontramos coincidencias':active==='inicio'?'No hay reservas pendientes':'Todavía no hay reservas'}</strong><p>{query||status!=='all'?'Prueba con otro término o estado.':'Las solicitudes aparecerán aquí cuando un cliente reserve.'}</p></td></tr>}</tbody></table></div></section>}
    {active==='cotizaciones'&&<section id="cotizaciones" className="admin-panel"><div className="admin-panel-heading"><div><h2>Solicitudes de cotización</h2><p>{pendingQuotes.length} pendientes de atención</p></div></div>{filters}<div className="quote-list">{visibleQuotes.map(q=><article className="admin-quote rounded-lg" key={q.id}><div className="quote-main"><span className={`admin-status ${q.status}`}>{q.status==='pending'?'Pendiente':q.status==='contacted'?'Contactada':'Cerrada'}</span><h3>{q.name}</h3><p>{q.customer} · {q.phone}</p><p className="quote-notes">{q.notes||'Sin detalles adicionales.'}</p>{q.link&&<a href={q.link} target="_blank" rel="noreferrer">Ver producto en la tienda <ExternalLink size={14}/></a>}</div><div className="row-actions">{q.status==='pending'&&<button className="action-confirm" disabled={busy!==null} onClick={()=>{window.open(`https://wa.me/51${q.phone}?text=${encodeURIComponent(`Hola ${q.customer}, recibimos tu solicitud de cotización de ${q.name}.`)}`,'_blank','noopener,noreferrer');void updateQuote(q.id,'contacted')}}><MessageCircle size={15}/>Contactar</button>}{q.status!=='closed'&&<button disabled={busy!==null} onClick={()=>updateQuote(q.id,'closed')}>Cerrar solicitud</button>}</div></article>)}{!visibleQuotes.length&&<div className="admin-empty"><MessageCircle size={26}/><strong>{query||status!=='all'?'No encontramos coincidencias':loading?'Cargando cotizaciones…':'Todavía no hay cotizaciones'}</strong><p>Las solicitudes de tus clientes aparecerán aquí.</p></div>}</div></section>}
    {active==='productos'&&<ProductManagement key={products.length}/>}{active==='clientes'&&<CustomerManagement/>}{active==='configuracion'&&role==='admin'&&<div className="admin-settings"><SettingsManagement/><UserManagement/><BackupManagement/><PasswordManagement/></div>}{active==='inicio'&&role!=='admin'&&<PasswordManagement/>}
  </main><footer className="admin-footer">NegroShop <span>Tu tienda, en orden.</span></footer></div>
  {open&&<Dialog label="Publicar producto" onClose={()=>{if(!publishing&&!processingPhotos)setOpen(false)}}><form onSubmit={publish} className="request-form"><div className="dialog-heading"><h2>Publicar producto</h2><button type="button" disabled={publishing||processingPhotos} onClick={()=>setOpen(false)} aria-label="Cerrar formulario"><X size={22}/></button></div><p className="form-description">Añade los detalles que verán tus compradores.</p><label>Nombre del producto<input name="name" required maxLength={200} placeholder="Nombre y modelo"/></label><label>Marca<input name="brand" required maxLength={120} placeholder="Marca del producto"/></label><label>Categoría<select name="category" required defaultValue="" onChange={e=>setCustomCategory(e.target.value==='__new__')}><option value="" disabled>Selecciona una categoría</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}<option value="__new__">Crear nueva categoría</option></select></label>{customCategory&&<label>Nueva categoría<input name="customCategory" required placeholder="Nombre de la categoría"/></label>}<div className="admin-form-columns"><label>Precio NegroShop<input name="price" required type="number" min="1" step="0.01" placeholder="0.00"/></label><label>Precio de referencia<input name="referencePrice" required type="number" min="1" step="0.01" placeholder="0.00"/></label></div><ProductPhotoUpload images={images} onChange={setImages} onBusyChange={setProcessingPhotos} disabled={publishing||processingPhotos}/><label className="photo-background-option"><input type="checkbox" checked={removeCoverBackground} onChange={e=>setRemoveCoverBackground(e.target.checked)} disabled={publishing||processingPhotos}/>Quitar el fondo de la foto de portada</label>{publishError&&<p className="error-message" role="alert">{publishError}</p>}<button className="primary-button" disabled={publishing||processingPhotos}>{publishing?'Procesando y publicando…':'Publicar producto'}<ArrowRight size={17}/></button></form></Dialog>}
  </div>
}
